export const   BUSCAEMAIL = 'BUSCAEMAIL';
export const   BUSCANOME  = 'BUSCANOME';
export const   BUSCAFOTO  = 'BUSCAFOTo';
export const   BUSCASENHA =  'BUSCASENHA';
export const   BUSCASENHAREPETIDA = 'BUSCASENHAREPETIDA';
export const   BUSCA_CPF = 'BUSCA_CPF';
export const   BUSCA_CONTATO = 'BUSCA_CONTATO';
export const   BUSCA_NIVEL = 'BUSCA_NIVEL';


export const BUSCA_CODIGO = 'BUSCA_CODIGO';
export const BUSCA_ENDERECO = 'BUSCA_ENDERECO';
export const BUSCA_DESTINATARIO= 'BUSCA_DESTINATARIO';
export const BUSCA_OBSERVACAO = 'BUSCA_OBSERVACAO';

export const BUSCA_LISTA_ENTREGA = 'BUSCA_LISTA_ENTREGA';
export const BUSCA_ITEM          =  'BUSCA_ITEM';


export const BUSCA_FOTO = 'BUSCA_FOTO';
export const  BUSCA_SEGUNDA_FOTO = 'BUSCA_SEGUNDA_FOTO';

export const BUSCA_UID = "BUSCA_UID";


export const BUSCA_BAIRRO = 'BUSCA_BAIRRO';
export const BUSCA_OPTIONS = 'BUSCA_OPTIONS';
export const BUSCA_EMPRESAS = 'BUSCA_EMPRESAS';

export const BUSCA_PLAN = 'BUSCA_PLAN';
export const FIND_INPUT_OCORRENCIA = 'FIND_INPUT_OCORRENCIA';
export const FIND_RADIO_OCORRENCIA = 'FIND_RADIO_OCORRENCIA';